version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database_data:/var/lib/postgresql/data


  api:
    restart: always
    container_name: api
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./api:/Users/ihsan/go/src/go_api/api
    depends_on:
      - db
    links:
      - db
# version: '3'
# services:
#   db:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     volumes:
#       - ./databse_data:/var/lib/postgresql/data
  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
# version: '3'

#   services:
#     api:
#       build: ./api
#       network_mode: bridge
#       environment:
#         - GO_ENV=production
#       restart: always
#       links:
#         - psql
#       volumes:
#         - ./databse_data:/var/lib/postgresql/data

#     psql:
#       image: postgres
#       network_mode: bridge
#       environment:
#         - POSTGRES_PASSWORD=postgres
#         - POSTGRES_USER=postgres
#       restart: always
#       volumes:
#       - ./databse_data:/var/lib/postgresql/data

