version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database_data:/var/lib/postgresql/data


  api:
    restart: always
    container_name: api
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./api:/Users/ihsan/go/src/go_api/api
    depends_on:
      - db

  client:
    build: ./client
    container_name: client
    ports:
      - "4200:4200"
      - "9876:9876"
    volumes:
      - ./client:/myapp
    working_dir: /myapp
    command: [sh, -c, npm install && npm start]  // if node module is not installed in the client use this 
    # command: [sh, -c,  npm start] // if node_module installed use this
    environment:
      - NODE_ENV=development